# FROM demonstrationorg/dhi-node:24.10-alpine3.22-dev
FROM demonstrationorg/dhi-node:24.10.0-dev
# FROM node:24.10
WORKDIR /usr/local/app

COPY package*.json ./
RUN npm install

COPY ./src ./src
EXPOSE 3000
CMD ["node", "src/index.js"]